version: "3.8"
networks:
    isolation-network:
        driver: bridge
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_DATABASE=strapi
        volumes:
            - ./mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        networks:
            - isolation-network

    auth_server:
        build : ./auth-server
        container_name: auth-server
        ports: 
            - 7000:7000
        depends_on: 
            - mongodb
        networks:
            - isolation-network
    strapi:
        container_name: strapi
        image: strapi/strapi
        environment:
            - DATABASE_CLIENT=mongo
            - DATABASE_HOST=db
            - DATABASE_PORT=27017
            - DATABASE_NAME=strapi
            - DATABASE_USERNAME=
            - DATABASE_PASSWORD=
            - AUTHENTICATION_DATABASE=strapi
        ports:
            - 1337:1337
        volumes:
            - ./app:/srv/app
        depends_on:
            - mongodb